apiVersion: v1
kind: Pod
metadata:
  name: slackbot
  labels:
    app: slackbot
spec:
  containers:
  - name: slackbot
    image: suberjin/slackbot-fastapi:0.0.1
    ports:
    - containerPort: 8000
    env:
      - name: API_KEY
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: API_KEY
      - name: SLACK_SIGNING_SECRET
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: SLACK_SIGNING_SECRET
      - name: SLACK_BOT_TOKEN
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: SLACK_BOT_TOKEN
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8000
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /readinez
        port: 8000
      initialDelaySeconds: 5
      periodSeconds: 10
